-- Cafe Napolitan - Supabase Database Schema
-- Run this in your Supabase SQL Editor to set up the database

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ============================================
-- Tables Table
-- ============================================
create table if not exists public.tables (
  id bigint generated by default as identity primary key,
  name text,
  seats integer not null default 4,
  shape text not null default 'circle' check (shape in ('circle', 'rectangle')),
  status text not null default 'available' check (status in ('available', 'occupied', 'preparing', 'awaiting', 'eating', 'reserved', 'cleaning')),
  floor integer not null default 1 check (floor in (1, 2)),
  group text not null default 'main',
  position_x integer not null default 0,
  position_y integer not null default 0,
  current_order_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.tables enable row level security;

-- Policies for tables
create policy "Allow all access to tables" on public.tables
  for all using (true) with check (true);

-- ============================================
-- Menu Items Table
-- ============================================
create table if not exists public.menu_items (
  id text primary key,
  name text not null,
  name_en text,
  category text not null,
  price integer not null,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.menu_items enable row level security;

-- Policies for menu_items
create policy "Allow all access to menu_items" on public.menu_items
  for all using (true) with check (true);

-- ============================================
-- Orders Table
-- ============================================
create table if not exists public.orders (
  id text primary key default uuid_generate_v4()::text,
  table_id bigint references public.tables(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'preparing', 'ready', 'served', 'paid', 'cancelled')),
  subtotal integer not null default 0,
  discount integer,
  total integer not null default 0,
  created_by bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.orders enable row level security;

-- Policies for orders
create policy "Allow all access to orders" on public.orders
  for all using (true) with check (true);

-- ============================================
-- Order Items Table
-- ============================================
create table if not exists public.order_items (
  id text primary key default uuid_generate_v4()::text,
  order_id text not null references public.orders(id) on delete cascade,
  menu_item_id text not null references public.menu_items(id) on delete restrict,
  quantity integer not null default 1,
  unit_price integer not null,
  notes text
);

-- Enable Row Level Security
alter table public.order_items enable row level security;

-- Policies for order_items
create policy "Allow all access to order_items" on public.order_items
  for all using (true) with check (true);

-- ============================================
-- Users Table
-- ============================================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  name text not null,
  role text not null default 'waiter' check (role in ('manager', 'kitchen', 'waiter')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.users enable row level security;

-- Policies for users
create policy "Allow all access to users" on public.users
  for all using (true) with check (true);

-- ============================================
-- Realtime Setup
-- ============================================
-- Enable realtime for all tables
alter publication supabase_realtime add table public.tables;
alter publication supabase_realtime add table public.menu_items;
alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.order_items;
alter publication supabase_realtime add table public.users;

-- ============================================
-- Seed Data: Default Tables
-- ============================================
insert into public.tables (name, seats, shape, status, floor, group, position_x, position_y) values
  ('میز ۱', 4, 'circle', 'available', 1, 'main', 0, 0),
  ('میز ۲', 4, 'circle', 'available', 1, 'main', 1, 0),
  ('میز ۳', 6, 'rectangle', 'available', 1, 'main', 2, 0),
  ('میز ۴', 2, 'circle', 'available', 1, 'window', 0, 1),
  ('میز ۵', 2, 'circle', 'available', 1, 'window', 1, 1),
  ('میز ۶', 8, 'rectangle', 'available', 2, 'vip', 0, 0),
  ('میز ۷', 4, 'circle', 'available', 2, 'vip', 1, 0),
  ('میز ۸', 4, 'circle', 'available', 2, 'vip', 2, 0)
on conflict do nothing;

-- ============================================
-- Seed Data: Menu Items
-- ============================================
insert into public.menu_items (id, name, name_en, category, price, available, sort_order) values
  -- Hot Coffee
  ('espresso', 'اسپرسو', 'Espresso', 'hot_coffee', 55000, true, 1),
  ('americano', 'آمریکانو', 'Americano', 'hot_coffee', 65000, true, 2),
  ('latte', 'لاته', 'Latte', 'hot_coffee', 75000, true, 3),
  ('cappuccino', 'کاپوچینو', 'Cappuccino', 'hot_coffee', 75000, true, 4),
  ('mocha', 'موکا', 'Mocha', 'hot_coffee', 85000, true, 5),
  -- Cold Coffee
  ('iced-latte', 'لاته سرد', 'Iced Latte', 'cold_coffee', 85000, true, 1),
  ('iced-americano', 'آمریکانو سرد', 'Iced Americano', 'cold_coffee', 75000, true, 2),
  ('cold-brew', 'کلد برو', 'Cold Brew', 'cold_coffee', 95000, true, 3),
  -- Hot Bar
  ('hot-chocolate', 'شکلات داغ', 'Hot Chocolate', 'hot_bar', 75000, true, 1),
  ('matcha-latte', 'ماتچا لاته', 'Matcha Latte', 'hot_bar', 95000, true, 2),
  ('chai-latte', 'چای لاته', 'Chai Latte', 'hot_bar', 75000, true, 3),
  -- Tea
  ('black-tea', 'چای سیاه', 'Black Tea', 'tea', 35000, true, 1),
  ('green-tea', 'چای سبز', 'Green Tea', 'tea', 40000, true, 2),
  ('herbal-tea', 'دمنوش', 'Herbal Tea', 'tea', 45000, true, 3),
  -- Frappe
  ('mocha-frappe', 'موکا فراپه', 'Mocha Frappe', 'frappe', 95000, true, 1),
  ('caramel-frappe', 'کارامل فراپه', 'Caramel Frappe', 'frappe', 95000, true, 2),
  ('vanilla-frappe', 'وانیل فراپه', 'Vanilla Frappe', 'frappe', 90000, true, 3),
  -- Shake Bar
  ('chocolate-shake', 'شیک شکلات', 'Chocolate Shake', 'shake_bar', 85000, true, 1),
  ('vanilla-shake', 'شیک وانیل', 'Vanilla Shake', 'shake_bar', 80000, true, 2),
  ('strawberry-shake', 'شیک توت فرنگی', 'Strawberry Shake', 'shake_bar', 90000, true, 3),
  -- Mojito
  ('classic-mojito', 'موهیتو کلاسیک', 'Classic Mojito', 'mojito', 85000, true, 1),
  ('berry-mojito', 'موهیتو توت', 'Berry Mojito', 'mojito', 95000, true, 2),
  -- Baked Potato
  ('baked-potato-cheese', 'سیب زمینی پنیری', 'Cheese Baked Potato', 'baked_potato', 125000, true, 1),
  ('baked-potato-bacon', 'سیب زمینی بیکن', 'Bacon Baked Potato', 'baked_potato', 145000, true, 2),
  -- Italian Plate
  ('pasta-carbonara', 'پاستا کاربونارا', 'Pasta Carbonara', 'italian_plate', 185000, true, 1),
  ('pasta-bolognese', 'پاستا بولونز', 'Pasta Bolognese', 'italian_plate', 175000, true, 2),
  ('risotto', 'ریزوتو', 'Risotto', 'italian_plate', 195000, true, 3),
  -- Burger
  ('classic-burger', 'برگر کلاسیک', 'Classic Burger', 'burger', 165000, true, 1),
  ('cheese-burger', 'چیزبرگر', 'Cheese Burger', 'burger', 185000, true, 2),
  ('double-burger', 'دبل برگر', 'Double Burger', 'burger', 225000, true, 3),
  -- Pizza
  ('margherita', 'پیتزا مارگاریتا', 'Margherita Pizza', 'pizza', 175000, true, 1),
  ('pepperoni', 'پیتزا پپرونی', 'Pepperoni Pizza', 'pizza', 195000, true, 2),
  ('vegetarian', 'پیتزا سبزیجات', 'Vegetarian Pizza', 'pizza', 165000, true, 3),
  -- Cake & Dessert
  ('cheesecake', 'چیزکیک', 'Cheesecake', 'cake_dessert', 95000, true, 1),
  ('tiramisu', 'تیرامیسو', 'Tiramisu', 'cake_dessert', 105000, true, 2),
  ('brownie', 'براونی', 'Brownie', 'cake_dessert', 75000, true, 3)
on conflict (id) do update set
  name = excluded.name,
  name_en = excluded.name_en,
  category = excluded.category,
  price = excluded.price,
  available = excluded.available,
  sort_order = excluded.sort_order;

-- ============================================
-- Seed Data: Users
-- ============================================
insert into public.users (id, username, name, role, is_active) values
  (1, 'manager', 'مدیریت', 'manager', true),
  (2, 'kitchen', 'آشپزخانه', 'kitchen', true),
  (3, 'waiter', 'گارسون', 'waiter', true)
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  is_active = excluded.is_active;

-- ============================================
-- Functions
-- ============================================

-- Function to update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger for tables
drop trigger if exists update_tables_updated_at on public.tables;
create trigger update_tables_updated_at
  before update on public.tables
  for each row execute function public.handle_updated_at();

-- Trigger for menu_items
drop trigger if exists update_menu_items_updated_at on public.menu_items;
create trigger update_menu_items_updated_at
  before update on public.menu_items
  for each row execute function public.handle_updated_at();

-- Trigger for orders
drop trigger if exists update_orders_updated_at on public.orders;
create trigger update_orders_updated_at
  before update on public.orders
  for each row execute function public.handle_updated_at();
