-- Cafe Napolitan - Supabase Database Schema
-- Complete database with proper RLS and Realtime
-- Run this in your Supabase SQL Editor to set up the database

-- ============================================
-- Enable Extensions
-- ============================================
create extension if not exists "uuid-ossp";

-- ============================================
-- APP USERS TABLE
-- Users with authentication and role-based access
-- ============================================
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  name text not null,
  role text not null default 'waiter' check (role in ('manager', 'kitchen', 'waiter')),
  is_active boolean not null default true,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_users enable row level security;

-- RLS: Anyone can see users, but only managers can modify
create policy "app_users_select" on public.app_users
  for select using (true);

create policy "app_users_insert" on public.app_users
  for insert with check (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

create policy "app_users_update" on public.app_users
  for update using (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

-- ============================================
-- MENU CATEGORIES TABLE
-- ============================================
create table if not exists public.menu_categories (
  id text primary key,
  name_fa text not null,
  name_en text,
  icon text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.menu_categories enable row level security;

-- RLS: Everyone can read categories, only managers can modify
create policy "menu_categories_select" on public.menu_categories
  for select using (true);

create policy "menu_categories_modify" on public.menu_categories
  for all using (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

-- ============================================
-- MENU ITEMS TABLE
-- ============================================
create table if not exists public.menu_items (
  id text primary key,
  name text not null,
  name_en text,
  category_id text not null references public.menu_categories(id),
  price integer not null check (price >= 0),
  description text,
  image_url text,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.menu_items enable row level security;

-- RLS: Everyone can read menu items, only managers can modify
create policy "menu_items_select" on public.menu_items
  for select using (true);

create policy "menu_items_available_update" on public.menu_items
  for update using (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'kitchen') and is_active = true
    )
  );

create policy "menu_items_modify" on public.menu_items
  for all using (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

-- ============================================
-- TABLES TABLE (Restaurant Tables)
-- ============================================
create table if not exists public.restaurant_tables (
  id bigint generated by default as identity primary key,
  name text,
  shape text not null default 'circle' check (shape in ('circle', 'rectangle')),
  group_name text not null default 'main',
  position_x integer not null default 0,
  position_y integer not null default 0,
  seats integer not null default 4 check (seats > 0),
  status text not null default 'available' check (status in ('available', 'occupied', 'preparing', 'awaiting', 'eating', 'reserved', 'cleaning')),
  floor integer not null default 1 check (floor in (1, 2)),
  current_order_id text,
  last_updated timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.restaurant_tables enable row level security;

-- RLS: All authenticated users can see and update tables
create policy "restaurant_tables_select" on public.restaurant_tables
  for select using (true);

create policy "restaurant_tables_update" on public.restaurant_tables
  for update using (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'waiter', 'kitchen') and is_active = true
    )
  );

create policy "restaurant_tables_insert" on public.restaurant_tables
  for insert with check (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

-- ============================================
-- ORDERS TABLE
-- ============================================
create table if not exists public.orders (
  id text primary key default uuid_generate_v4()::text,
  table_id bigint references public.restaurant_tables(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'preparing', 'ready', 'served', 'paid', 'cancelled')),
  subtotal integer not null default 0 check (subtotal >= 0),
  discount integer default 0 check (discount >= 0),
  discount_percent integer check (discount_percent >= 0 and discount_percent <= 100),
  tax integer default 0 check (tax >= 0),
  tax_percent integer check (tax_percent >= 0 and tax_percent <= 100),
  total integer not null default 0 check (total >= 0),
  created_by bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- RLS: All users can see orders, kitchen can update status, manager can do all
create policy "orders_select" on public.orders
  for select using (true);

create policy "orders_insert" on public.orders
  for insert with check (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'waiter') and is_active = true
    )
  );

create policy "orders_update_status" on public.orders
  for update using (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'kitchen', 'waiter') and is_active = true
    )
  );

-- ============================================
-- ORDER ITEMS TABLE
-- ============================================
create table if not exists public.order_items (
  id text primary key default uuid_generate_v4()::text,
  order_id text not null references public.orders(id) on delete cascade,
  menu_item_id text not null references public.menu_items(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  notes text,
  created_at timestamptz not null default now()
);

alter table public.order_items enable row level security;

-- RLS: All users can see items, waiters can add/remove items
create policy "order_items_select" on public.order_items
  for select using (true);

create policy "order_items_insert" on public.order_items
  for insert with check (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'waiter') and is_active = true
    )
  );

create policy "order_items_delete" on public.order_items
  for delete using (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'waiter') and is_active = true
    )
  );

-- ============================================
-- TAKEAWAY ORDERS TABLE
-- ============================================
create table if not exists public.takeaway_orders (
  id text primary key default uuid_generate_v4()::text,
  customer_name text,
  customer_phone text,
  status text not null default 'pending' check (status in ('pending', 'preparing', 'ready', 'delivered', 'cancelled')),
  subtotal integer not null default 0,
  total integer not null default 0,
  notes text,
  created_by bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.takeaway_orders enable row level security;

-- RLS: All users can see takeaway orders
create policy "takeaway_orders_select" on public.takeaway_orders
  for select using (true);

create policy "takeaway_orders_insert" on public.takeaway_orders
  for insert with check (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'waiter') and is_active = true
    )
  );

create policy "takeaway_orders_update" on public.takeaway_orders
  for update using (
    exists (
      select 1 from public.app_users 
      where role in ('manager', 'kitchen', 'waiter') and is_active = true
    )
  );

-- ============================================
-- AUDIT LOG TABLE
-- ============================================
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_value jsonb,
  new_value jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

-- RLS: Only managers can view audit log, but all actions are logged
create policy "audit_log_select" on public.audit_log
  for select using (
    exists (
      select 1 from public.app_users 
      where role = 'manager' and is_active = true
    )
  );

create policy "audit_log_insert" on public.audit_log
  for insert with check (true);

-- ============================================
-- REALTIME SETUP
-- ============================================
alter publication supabase_realtime add table public.restaurant_tables;
alter publication supabase_realtime add table public.menu_items;
alter publication supabase_realtime add table public.menu_categories;
alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.order_items;
alter publication supabase_realtime add table public.takeaway_orders;

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function to update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Function to log audit entries
create or replace function public.log_audit()
returns trigger as $$
begin
  insert into public.audit_log (user_id, action, entity_type, entity_id, old_value, new_value)
  values (
    current_setting('request.jwt.claims', true)::jsonb->>'user_id',
    TG_OP,
    TG_TABLE_NAME,
    coalesce(new.id, old.id),
    case when TG_OP = 'UPDATE' then to_jsonb(old) else null end,
    case when TG_OP in ('UPDATE', 'INSERT') then to_jsonb(new) else null end
  );
  return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
drop trigger if exists update_restaurant_tables_updated_at on public.restaurant_tables;
create trigger update_restaurant_tables_updated_at
  before update on public.restaurant_tables
  for each row execute function public.handle_updated_at();

drop trigger if exists update_menu_items_updated_at on public.menu_items;
create trigger update_menu_items_updated_at
  before update on public.menu_items
  for each row execute function public.handle_updated_at();

drop trigger if exists update_orders_updated_at on public.orders;
create trigger update_orders_updated_at
  before update on public.orders
  for each row execute function public.handle_updated_at();

drop trigger if exists update_takeaway_orders_updated_at on public.takeaway_orders;
create trigger update_takeaway_orders_updated_at
  before update on public.takeaway_orders
  for each row execute function public.handle_updated_at();

drop trigger if exists update_app_users_updated_at on public.app_users;
create trigger update_app_users_updated_at
  before update on public.app_users
  for each row execute function public.handle_updated_at();

-- ============================================
-- SEED DATA: Menu Categories
-- ============================================
insert into public.menu_categories (id, name_fa, name_en, icon, sort_order) values
  ('hot_coffee', 'کافه گرم', 'Hot Coffee', '☕', 1),
  ('cold_coffee', 'کافه سرد', 'Cold Coffee', '🧊', 2),
  ('hot_bar', 'بار گرم', 'Hot Bar', '🍫', 3),
  ('tea', 'چای', 'Tea', '🍵', 4),
  ('frappe', 'فراپه', 'Frappe', '🥤', 5),
  ('shake_bar', 'بار شیک', 'Shake Bar', '🥛', 6),
  ('mojito', 'موهیتو', 'Mojito', '🍹', 7),
  ('baked_potato', 'سیب زمینی', 'Baked Potato', '🥔', 8),
  ('italian_plate', 'پاستا', 'Italian Plate', '🍝', 9),
  ('burger', 'برگر', 'Burger', '🍔', 10),
  ('pizza', 'پیتزا', 'Pizza', '🍕', 11),
  ('cake_dessert', 'کیک و دسر', 'Cake & Dessert', '🍰', 12)
on conflict (id) do update set
  name_fa = excluded.name_fa,
  name_en = excluded.name_en,
  icon = excluded.icon,
  sort_order = excluded.sort_order;

-- ============================================
-- SEED DATA: Menu Items
-- ============================================
insert into public.menu_items (id, name, name_en, category_id, price, available, sort_order) values
  -- Hot Coffee
  ('espresso', 'اسپرسو', 'Espresso', 'hot_coffee', 55000, true, 1),
  ('americano', 'آمریکانو', 'Americano', 'hot_coffee', 65000, true, 2),
  ('latte', 'لاته', 'Latte', 'hot_coffee', 75000, true, 3),
  ('cappuccino', 'کاپوچینو', 'Cappuccino', 'hot_coffee', 75000, true, 4),
  ('mocha', 'موکا', 'Mocha', 'hot_coffee', 85000, true, 5),
  -- Cold Coffee
  ('iced-latte', 'لاته سرد', 'Iced Latte', 'cold_coffee', 85000, true, 1),
  ('iced-americano', 'آمریکانو سرد', 'Iced Americano', 'cold_coffee', 75000, true, 2),
  ('cold-brew', 'کلد برو', 'Cold Brew', 'cold_coffee', 95000, true, 3),
  -- Hot Bar
  ('hot-chocolate', 'شکلات داغ', 'Hot Chocolate', 'hot_bar', 75000, true, 1),
  ('matcha-latte', 'ماتچا لاته', 'Matcha Latte', 'hot_bar', 95000, true, 2),
  ('chai-latte', 'چای لاته', 'Chai Latte', 'hot_bar', 75000, true, 3),
  -- Tea
  ('black-tea', 'چای سیاه', 'Black Tea', 'tea', 35000, true, 1),
  ('green-tea', 'چای سبز', 'Green Tea', 'tea', 40000, true, 2),
  ('herbal-tea', 'دمنوش', 'Herbal Tea', 'tea', 45000, true, 3),
  -- Frappe
  ('mocha-frappe', 'موکا فراپه', 'Mocha Frappe', 'frappe', 95000, true, 1),
  ('caramel-frappe', 'کارامل فراپه', 'Caramel Frappe', 'frappe', 95000, true, 2),
  ('vanilla-frappe', 'وانیل فراپه', 'Vanilla Frappe', 'frappe', 90000, true, 3),
  -- Shake Bar
  ('chocolate-shake', 'شیک شکلات', 'Chocolate Shake', 'shake_bar', 85000, true, 1),
  ('vanilla-shake', 'شیک وانیل', 'Vanilla Shake', 'shake_bar', 80000, true, 2),
  ('strawberry-shake', 'شیک توت فرنگی', 'Strawberry Shake', 'shake_bar', 90000, true, 3),
  -- Mojito
  ('classic-mojito', 'موهیتو کلاسیک', 'Classic Mojito', 'mojito', 85000, true, 1),
  ('berry-mojito', 'موهیتو توت', 'Berry Mojito', 'mojito', 95000, true, 2),
  -- Baked Potato
  ('baked-potato-cheese', 'سیب زمینی پنیری', 'Cheese Baked Potato', 'baked_potato', 125000, true, 1),
  ('baked-potato-bacon', 'سیب زمینی بیکن', 'Bacon Baked Potato', 'baked_potato', 145000, true, 2),
  -- Italian Plate
  ('pasta-carbonara', 'پاستا کاربونارا', 'Pasta Carbonara', 'italian_plate', 185000, true, 1),
  ('pasta-bolognese', 'پاستا بولونز', 'Pasta Bolognese', 'italian_plate', 175000, true, 2),
  ('risotto', 'ریزوتو', 'Risotto', 'italian_plate', 195000, true, 3),
  -- Burger
  ('classic-burger', 'برگر کلاسیک', 'Classic Burger', 'burger', 165000, true, 1),
  ('cheese-burger', 'چیزبرگر', 'Cheese Burger', 'burger', 185000, true, 2),
  ('double-burger', 'دبل برگر', 'Double Burger', 'burger', 225000, true, 3),
  -- Pizza
  ('margherita', 'پیتزا مارگاریتا', 'Margherita Pizza', 'pizza', 175000, true, 1),
  ('pepperoni', 'پیتزا پپرونی', 'Pepperoni Pizza', 'pizza', 195000, true, 2),
  ('vegetarian', 'پیتزا سبزیجات', 'Vegetarian Pizza', 'pizza', 165000, true, 3),
  -- Cake & Dessert
  ('cheesecake', 'چیزکیک', 'Cheesecake', 'cake_dessert', 95000, true, 1),
  ('tiramisu', 'تیرامیسو', 'Tiramisu', 'cake_dessert', 105000, true, 2),
  ('brownie', 'براونی', 'Brownie', 'cake_dessert', 75000, true, 3)
on conflict (id) do update set
  name = excluded.name,
  name_en = excluded.name_en,
  category_id = excluded.category_id,
  price = excluded.price,
  available = excluded.available,
  sort_order = excluded.sort_order;

-- ============================================
-- SEED DATA: Restaurant Tables
-- ============================================
insert into public.restaurant_tables (name, seats, shape, status, floor, group_name, position_x, position_y) values
  ('میز ۱', 4, 'circle', 'available', 1, 'main', 0, 0),
  ('میز ۲', 4, 'circle', 'available', 1, 'main', 1, 0),
  ('میز ۳', 6, 'rectangle', 'available', 1, 'main', 2, 0),
  ('میز ۴', 2, 'circle', 'available', 1, 'window', 0, 1),
  ('میز ۵', 2, 'circle', 'available', 1, 'window', 1, 1),
  ('میز ۶', 8, 'rectangle', 'available', 2, 'vip', 0, 0),
  ('میز ۷', 4, 'circle', 'available', 2, 'vip', 1, 0),
  ('میز ۸', 4, 'circle', 'available', 2, 'vip', 2, 0)
on conflict do nothing;

-- ============================================
-- SEED DATA: App Users (Password: same as username + '123')
-- In production, use properly hashed passwords!
-- ============================================
insert into public.app_users (id, username, password_hash, name, role, is_active) values
  (1, 'manager', 'manager123', 'مدیریت', 'manager', true),
  (2, 'kitchen', 'kitchen123', 'آشپزخانه', 'kitchen', true),
  (3, 'waiter', 'waiter123', 'گارسون', 'waiter', true)
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  is_active = excluded.is_active;
